// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TransactionType,
} from "./types";

export default {
  title: __t.string(),
  get type() {
    return TransactionType;
  },
  amount: __t.u64(),
  timestamp: __t.timestamp(),
  walletId: __t.u64(),
  categoryId: __t.option(__t.u64()),
  subCategoryId: __t.option(__t.u64()),
  toWalletId: __t.option(__t.u64()),
  notes: __t.option(__t.string()),
  tags: __t.array(__t.string()),
};
