// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TaskPriority,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  ownerId: __t.identity().name("owner_id"),
  name: __t.string(),
  deadline: __t.option(__t.timestamp()),
  get priority() {
    return TaskPriority;
  },
  effort: __t.option(__t.u32()),
  difficulty: __t.option(__t.u8()),
  categoryId: __t.option(__t.u64()).name("category_id"),
  description: __t.option(__t.string()),
  tags: __t.array(__t.string()),
  isCompleted: __t.bool().name("is_completed"),
});
