// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TransactionType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  ownerId: __t.identity().name("owner_id"),
  name: __t.string(),
  get type() {
    return TransactionType;
  },
  icon: __t.string(),
  color: __t.string(),
});
