// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TransactionType,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  ownerId: __t.identity().name("owner_id"),
  title: __t.string(),
  get type() {
    return TransactionType;
  },
  amount: __t.u64(),
  timestamp: __t.timestamp(),
  walletId: __t.u64().name("wallet_id"),
  categoryId: __t.option(__t.u64()).name("category_id"),
  subCategoryId: __t.option(__t.u64()).name("sub_category_id"),
  linkedTransactionId: __t.option(__t.u64()).name("linked_transaction_id"),
  notes: __t.option(__t.string()),
  tags: __t.array(__t.string()),
});
