// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `Currency`.
export const Currency = __t.enum("Currency", {
  Idr: __t.unit(),
  Usd: __t.unit(),
});
export type Currency = __Infer<typeof Currency>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  ownerId: __t.identity(),
  name: __t.string(),
  deadline: __t.option(__t.timestamp()),
  get priority() {
    return TaskPriority;
  },
  effort: __t.option(__t.u32()),
  difficulty: __t.option(__t.u8()),
  categoryId: __t.option(__t.u64()),
  description: __t.option(__t.string()),
  tags: __t.array(__t.string()),
  isCompleted: __t.bool(),
});
export type Task = __Infer<typeof Task>;

export const TaskCategory = __t.object("TaskCategory", {
  id: __t.u64(),
  ownerId: __t.identity(),
  name: __t.string(),
  icon: __t.string(),
  color: __t.string(),
});
export type TaskCategory = __Infer<typeof TaskCategory>;

// The tagged union or sum type for the algebraic type `TaskPriority`.
export const TaskPriority = __t.enum("TaskPriority", {
  Low: __t.unit(),
  Medium: __t.unit(),
  High: __t.unit(),
});
export type TaskPriority = __Infer<typeof TaskPriority>;

export const Transaction = __t.object("Transaction", {
  id: __t.u64(),
  ownerId: __t.identity(),
  title: __t.string(),
  get type() {
    return TransactionType;
  },
  amount: __t.u64(),
  timestamp: __t.timestamp(),
  walletId: __t.u64(),
  categoryId: __t.option(__t.u64()),
  subCategoryId: __t.option(__t.u64()),
  linkedTransactionId: __t.option(__t.u64()),
  notes: __t.option(__t.string()),
  tags: __t.array(__t.string()),
});
export type Transaction = __Infer<typeof Transaction>;

export const TransactionCategory = __t.object("TransactionCategory", {
  id: __t.u64(),
  ownerId: __t.identity(),
  name: __t.string(),
  get type() {
    return TransactionType;
  },
  icon: __t.string(),
  color: __t.string(),
});
export type TransactionCategory = __Infer<typeof TransactionCategory>;

export const TransactionSubcategory = __t.object("TransactionSubcategory", {
  id: __t.u64(),
  ownerId: __t.identity(),
  categoryId: __t.u64(),
  name: __t.string(),
  icon: __t.option(__t.string()),
});
export type TransactionSubcategory = __Infer<typeof TransactionSubcategory>;

// The tagged union or sum type for the algebraic type `TransactionType`.
export const TransactionType = __t.enum("TransactionType", {
  Income: __t.unit(),
  Expense: __t.unit(),
  Transfer: __t.unit(),
  Correction: __t.unit(),
});
export type TransactionType = __Infer<typeof TransactionType>;

export const Wallet = __t.object("Wallet", {
  id: __t.u64(),
  ownerId: __t.identity(),
  name: __t.string(),
  get type() {
    return WalletType;
  },
  balance: __t.i64(),
  get currency() {
    return Currency;
  },
  icon: __t.string(),
  color: __t.string(),
});
export type Wallet = __Infer<typeof Wallet>;

// The tagged union or sum type for the algebraic type `WalletType`.
export const WalletType = __t.enum("WalletType", {
  Cash: __t.unit(),
  Bank: __t.unit(),
  Ewallet: __t.unit(),
  CreditCard: __t.unit(),
});
export type WalletType = __Infer<typeof WalletType>;

