// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateTaskReducer from "../create_task_reducer";
import CreateTaskCategoryReducer from "../create_task_category_reducer";
import CreateTransactionReducer from "../create_transaction_reducer";
import CreateTxCategoryReducer from "../create_tx_category_reducer";
import CreateTxSubcategoryReducer from "../create_tx_subcategory_reducer";
import CreateWalletReducer from "../create_wallet_reducer";
import DeleteTaskReducer from "../delete_task_reducer";
import DeleteTaskCategoryReducer from "../delete_task_category_reducer";
import DeleteTransactionReducer from "../delete_transaction_reducer";
import DeleteTxCategoryReducer from "../delete_tx_category_reducer";
import DeleteTxSubcategoryReducer from "../delete_tx_subcategory_reducer";
import DeleteWalletReducer from "../delete_wallet_reducer";
import ToggleTaskCompletionReducer from "../toggle_task_completion_reducer";
import UpdateTaskReducer from "../update_task_reducer";
import UpdateTaskCategoryReducer from "../update_task_category_reducer";
import UpdateTransactionReducer from "../update_transaction_reducer";
import UpdateTxCategoryReducer from "../update_tx_category_reducer";
import UpdateTxSubcategoryReducer from "../update_tx_subcategory_reducer";
import UpdateWalletReducer from "../update_wallet_reducer";

export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type CreateTaskCategoryParams = __Infer<typeof CreateTaskCategoryReducer>;
export type CreateTransactionParams = __Infer<typeof CreateTransactionReducer>;
export type CreateTxCategoryParams = __Infer<typeof CreateTxCategoryReducer>;
export type CreateTxSubcategoryParams = __Infer<typeof CreateTxSubcategoryReducer>;
export type CreateWalletParams = __Infer<typeof CreateWalletReducer>;
export type DeleteTaskParams = __Infer<typeof DeleteTaskReducer>;
export type DeleteTaskCategoryParams = __Infer<typeof DeleteTaskCategoryReducer>;
export type DeleteTransactionParams = __Infer<typeof DeleteTransactionReducer>;
export type DeleteTxCategoryParams = __Infer<typeof DeleteTxCategoryReducer>;
export type DeleteTxSubcategoryParams = __Infer<typeof DeleteTxSubcategoryReducer>;
export type DeleteWalletParams = __Infer<typeof DeleteWalletReducer>;
export type ToggleTaskCompletionParams = __Infer<typeof ToggleTaskCompletionReducer>;
export type UpdateTaskParams = __Infer<typeof UpdateTaskReducer>;
export type UpdateTaskCategoryParams = __Infer<typeof UpdateTaskCategoryReducer>;
export type UpdateTransactionParams = __Infer<typeof UpdateTransactionReducer>;
export type UpdateTxCategoryParams = __Infer<typeof UpdateTxCategoryReducer>;
export type UpdateTxSubcategoryParams = __Infer<typeof UpdateTxSubcategoryReducer>;
export type UpdateWalletParams = __Infer<typeof UpdateWalletReducer>;

